In [2]:


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [12]:
df = pd.read_csv("C:/Users/rp960/Documents/Jupyter/Indian-Crime-Prediction-and-Visualization-Online-Platform-master/static/CAW.csv")
df

,Year,Rape,Kidnapping and Abduction of Women & Girls,Dowry Deaths,Assault on women with intent to outrage her modesty,Insult to the modesty of Women,Cruelty by Husband or his relatives,Importation of Girls from Foreign Country,Immoral Traffic (P) Act,Dowry Prohibition Act,Indecent Representation of Women (P) Act,Commission of Sati (P) Act,Total Crimes against Women
0,2001,16075,14645,6851,34124,9746,49170,114,8796,3222,1052,0,143795
1,2002,16373,14506,6822,33943,10155,49237,76,6598,2816,2508,0,143034
2,2003,15847,13296,6208,32939,12325,50703,46,5510,2684,1043,0,140601
3,2004,18233,15578,7026,34567,10001,58121,89,5748,3592,1378,0,154333
4,2005,18359,15750,6787,34175,9984,58319,149,5908,3204,2917,1,155553
5,2006,19348,17414,7618,36617,9966,63128,67,4541,4504,1562,0,164765
6,2007,20737,20416,8093,38734,10950,75930,61,3568,5623,1200,0,185312
7,2008,21467,22939,8172,40413,12214,81344,67,2660,5555,1025,1,195857
8,2009,21397,25741,8383,38711,11009,89546,48,2474,5650,845,0,203804
9,2010,22172,29795,8391,40613,9961,94041,36,2499,5182,895,0,213585
10,2011,24206,35565,8618,42968,8570,99135,80,2435,6619,453,1,228650
11,2012,24923,38262,8233,45351,9173,106527,59,2563,9038,141,0,244270
12,2013,33707,51881,8083,70739,12589,118866,31,2579,10709,362,0,309546
13,2014,36735,57311,8455,82235,9735,122877,13,2070,10050,47,0,329528
14,2015,34651,59277,7634,82422,8685,113403,6,2424,9894,40,0,318436
15,2016,38947,64519,7621,84746,7305,110378,12,2214,9683,38,0,325463

In [14]:
X = df.iloc[:,:-1].values
y = df.iloc[:,12].values
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

regressor = LinearRegression()
regressor.fit(X_train,y_train)

print ("Your Test Set is:- \n",X_test)
#X_tst = np.array([2015, 0, 0,  0, 0, 0, 0, 0, 0, 0,  0, 0])
accuracy = regressor.score(X_test,y_test)
print ("\nYour Prediction has the accuracy of :-",accuracy*100,"%")

y_prediction = regressor.predict(X_test)
print ("\nPredicted Total Crime for above given years is:-\n",y_prediction)

Your Test Set is:-
 [[  2002  16373  14506   6822  33943  10155  49237     76   6598   2816
    2508      0]
 [  2001  16075  14645   6851  34124   9746  49170    114   8796   3222
    1052      0]
 [  2013  33707  51881   8083  70739  12589 118866     31   2579  10709
     362      0]
 [  2009  21397  25741   8383  38711  11009  89546     48   2474   5650
     845      0]]

Your Prediction has the accuracy of :- 99.99999974215508 %

Predicted Total Crime for above given years is:-
 [143036.09179538 143800.60858563 309549.41425933 203803.94317916]

In [15]:
rapeX = df.iloc[:,0].values
rapeY = df.iloc[:,1].values

#rapeX_train,rapeX_test,rapeY_train,rapeY_test = cross_validation.train_test_split(rapeX,rapeY,test_size=0.1)
rapeX_test = np.array([2015,2016,2017,2018,2019,2020])

print ("Your Test Set is:- \n",rapeX_test)

clf=LinearRegression()    #clf is the regression classifier
clf.fit(rapeX.reshape(-1, 1),rapeY)   #reshape to convert it from 1 dimentional array to 2D array.
#accuracy = clf.score(rapeX_test.reshape(-1, 1),rapeY_test)
#print accuracy
rapePredict = clf.predict(rapeX_test.reshape(-1,1))
print ("\nPredicted Total Crime for above given years is:-\n",rapePredict)

Your Test Set is:-
 [2015 2016 2017 2018 2019 2020]

Predicted Total Crime for above given years is:-
 [33738.71911765 35244.89705882 36751.075      38257.25294118
 39763.43088235 41269.60882353]

In [19]:

'''plt.scatter(rapeX,rapeY,color = 'red')
plt.plot(rapeX, clf.predict(rapeX.reshape(1,-1)), color = 'blue')

plt.title("Rape Crime against Women")
plt.xlabel("Year")
plt.ylabel("Rape Cases Reported")
plt.show()
'''

'plt.scatter(rapeX,rapeY,color = \'red\')\nplt.plot(rapeX, clf.predict(rapeX.reshape(1,-1)), color = \'blue\')\n\nplt.title("Rape Crime against Women")\nplt.xlabel("Year")\nplt.ylabel("Rape Cases Reported")\nplt.show()\n'